documentation:
- changed-files:
  - any-glob-to-any-file:
    - "doc/source/*"
    - "README.md"

maintenance:
- changed-files:
  - any-glob-to-any-file:
    - ".github/**/*"
    - ".flake8"
    - "pyproject.toml"

testing:
- changed-files:
  - any-glob-to-any-file:
    - "tests/conftest.py"
    - "tests/tests_aedt/conftest.py"
