//Language: OlaruScript

// states
State=snormal
State=sproperty
State=sexternal
State=sstring
State=sstring2
State=scomment1
State=scomment2
State=scomment3
// tokens
Token=tNone
Token=tcommand
Token=tcomandparameter
Token=tkeyword
Token=tfunction
Token=tident
Token=tstring
Token=tinteger
Token=tfloat
Token=tresword
Token=tcomment
Token=tbackcompatible
Token=twhitespace

//delims
Delimiters=;.,:'"{}[]()?!@#$%^&*-+=|\/

// reswords
snormal 'Procedure'   snormal tcommand
snormal 'Setting'   snormal tcommand
snormal 'I_O'   snormal tcommand
snormal 'Geometry'   snormal tcommand
snormal 'PreProcessing'   snormal tcommand
snormal 'Solving'   snormal tcommand
snormal 'PostProcessing'   snormal tcommand
snormal 'Computations'   snormal tcommand
snormal 'General'   snormal tcommand
snormal 'Let'   snormal tcommand
snormal 'Call'   snormal tcommand
snormal 'Repeat'   snormal tcommand
snormal 'END'   snormal tcommand
snormal 'If'   snormal tcommand
snormal 'Else'   snormal tcommand
snormal 'EndIf'   snormal tcommand
snormal 'Pause'   snormal tcommand
snormal 'Do'   snormal tcommand
snormal 'Cycle'   snormal tcommand
snormal 'ExitDo'   snormal tcommand
snormal 'EndDo'   snormal tcommand
snormal 'DoCase'   snormal tcommand
snormal 'Case'   snormal tcommand
snormal 'Skip'   snormal tcommand
snormal 'EndCase'   snormal tcommand
snormal 'Return'   snormal tcommand
snormal 'Exit'   snormal tcommand
snormal 'CaseSensitive'   snormal tcommand
snormal 'SetInputUnits'   snormal tcommand
snormal 'SetReportUnits'   snormal tcommand
snormal 'ParTable'   snormal tcommand
snormal 'Parameters'   snormal tcommand
snormal 'LoadParFromFile'   snormal tcommand
snormal 'InputPAR'   snormal tcommand
snormal 'SaveParToFile'   snormal tcommand
snormal 'Listing'   snormal tcommand
snormal 'Report'   snormal tcommand
snormal 'Report_file'   snormal tbackcompatible
snormal 'Report_text'   snormal tcommand
snormal 'ShowCaption'   snormal tcommand
snormal 'ShowMessage'   snormal tcommand
snormal 'ShowProgressBar'   snormal tcommand
snormal 'HideProgressBar'   snormal tcommand
snormal 'InitStack'   snormal tcommand
snormal 'AddToStack'   snormal tcommand
snormal 'Assign'   snormal tcommand
snormal 'WriteLn'   snormal tcommand
snormal 'Write'   snormal tcommand
snormal 'Readln'   snormal tcommand
snormal 'Read'   snormal tcommand
snormal 'Close'   snormal tcommand
snormal 'PosInputFile'   snormal tcommand
snormal 'BNDTitle'   snormal tcommand
snormal 'ClearGeometry'   snormal tcommand
snormal 'LoadGeometry'   snormal tcommand
snormal 'InsertFile'   snormal tcommand
snormal 'Line'   snormal tcommand
snormal 'Arc'   snormal tcommand
snormal 'Angle'   snormal tcomandparameter
snormal 'Point'   snormal tcommand
snormal 'EditGeometry'   snormal tcommand
snormal 'SaveGeometryAs'   snormal tcommand
snormal 'SaveRegions'   snormal tcommand
snormal 'FullIntersections'   snormal tcommand
snormal 'GenerateBnd'   snormal tcommand
snormal 'SaveBND'   snormal tcommand
snormal 'MeshTitle'   snormal tcommand
snormal 'OpenBND'   snormal tcommand
snormal 'Mesh'   snormal tcommand
snormal 'Optim_mesh'   snormal tcommand
snormal 'FullOptim'   snormal tcommand
snormal 'SurfOptim'   snormal tcommand
snormal 'DivideTriangles'   snormal tcommand
snormal 'DeleteTriangles'   snormal tcommand
snormal 'D_Test'   snormal tcommand
snormal 'Centered'   snormal tcommand
snormal 'Set_Bnd_Conditions'   snormal tcommand
snormal 'Save'   snormal tcommand
snormal 'Title'   snormal tcommand
snormal 'Input'   snormal tcommand
snormal 'Output'   snormal tcommand
snormal 'Compare'   snormal tcommand
snormal 'Problem'   snormal tcommand
snormal 'BH_file'   snormal tcommand
snormal 'Regions'   snormal tcommand
snormal 'LoadRegions'   snormal tcommand
snormal 'Region'   snormal tcommand
snormal 'ClearCircuit'   snormal tcommand
snormal 'Series_Coils'   snormal tcommand
snormal 'Parallel_Coils'   snormal tcommand
snormal 'SetAConstant'   snormal tcommand
snormal 'Dirichlet'   snormal tbackcompatible
snormal 'SetdAdn'   snormal tcommand
snormal 'SetMixedBnd'   snormal tcommand
snormal 'Rotate'   snormal tcommand
snormal 'Rotate_Magnetisation'   snormal tcommand
snormal 'Translate'   snormal tcommand
snormal 'AutoAdaptive'   snormal tcommand
snormal 'Compute'   snormal tcommand
snormal 'Open'   snormal tcommand
snormal 'FirstSolution'   snormal tcommand
snormal 'LastSolution'   snormal tcommand
snormal 'NextSolution'   snormal tcommand
snormal 'ZonePaint'   snormal tcommand
snormal 'LineDraw'   snormal tcommand
snormal 'Function'   snormal tcomandparameter
snormal 'VectorDraw'   snormal tcommand
snormal 'MeshDraw'   snormal tcommand
snormal 'PointsTable'   snormal tcommand
snormal 'ElementsTable'   snormal tcommand
snormal 'Flux_linkage'   snormal tcommand
snormal 'Flux'   snormal tcommand
snormal 'EnergyJA'   snormal tcommand
snormal 'Energy'   snormal tcommand
snormal 'CoEnergy'   snormal tcommand
snormal 'Integral'   snormal tcommand
snormal 'Inertia'   snormal tcommand
snormal 'SiTorque'   snormal tcommand
snormal 'SiForce'   snormal tcommand
snormal 'SelectPoint'   snormal tcommand
snormal 'Measure_arc'   snormal tcommand
snormal 'Measure_line'   snormal tcommand
snormal 'Conditions'   snormal tcommand
snormal 'FullSection'   snormal tcommand
snormal 'Copy'   snormal tcommand
snormal 'Move'   snormal tcommand
snormal 'Draw'   snormal tcommand
snormal 'DrawChart'   snormal tcommand
snormal 'ComputeLOSS'   snormal tcommand
snormal 'LossData'   snormal tcommand
snormal 'Argument'   snormal tcomandparameter
snormal 'ShowRepetitions'   snormal tcomandparameter
snormal 'ShowProgress'   snormal tcomandparameter
snormal 'When'   snormal tcomandparameter
snormal 'While'   snormal tcomandparameter
snormal 'Times'   snormal tcomandparameter
snormal 'To'   snormal tcomandparameter
snormal 'Variables'   snormal tcomandparameter
snormal 'Default'   snormal tcomandparameter
snormal 'LengthMode'   snormal tcomandparameter
snormal 'AreaMode'   snormal tcomandparameter
snormal 'JMode'   snormal tcomandparameter
snormal 'PotentialMode'   snormal tcomandparameter
snormal 'HMode'   snormal tcomandparameter
snormal 'BMode'   snormal tcomandparameter
snormal 'FluxMode'   snormal tcomandparameter
snormal 'TORQUEMode'   snormal tcomandparameter
snormal 'ForceMode'   snormal tcomandparameter
snormal 'EnergyMode'   snormal tcomandparameter
snormal 'EnergyJaMode'   snormal tcomandparameter
snormal 'InertiaMode'   snormal tcomandparameter
snormal 'DensityMode'   snormal tcomandparameter
snormal 'FDMode'   snormal tcomandparameter
snormal 'ParList'   snormal tcomandparameter
snormal 'Short_list'   snormal tcomandparameter
snormal 'All_List'   snormal tcomandparameter
snormal 'Append'   snormal tcomandparameter
snormal 'Rewrite'   snormal tcomandparameter
snormal 'Name'   snormal tcomandparameter
snormal 'BarPosition'   snormal tcomandparameter
snormal 'Min'   snormal tcomandparameter
snormal 'Max'   snormal tcomandparameter
snormal 'StackCount'   snormal tcomandparameter
snormal 'ShowAsMessage'   snormal tcomandparameter
snormal 'Label'   snormal tcomandparameter
snormal 'Index'   snormal tcomandparameter
snormal 'NumValue'   snormal tcomandparameter
snormal 'StrValue'   snormal tcomandparameter
snormal 'Ch'   snormal tcomandparameter
snormal 'Inp'   snormal tbackcompatible
snormal 'Out'   snormal tbackcompatible
snormal 'App'   snormal tbackcompatible
snormal 'ExpList'   snormal tcomandparameter
snormal 'Format'   snormal tcomandparameter
snormal 'VarList'   snormal tcomandparameter
snormal 'IndexLine'   snormal tcomandparameter
snormal 'Find'   snormal tcomandparameter
snormal 'FindNext'   snormal tcomandparameter
snormal 'Range'   snormal tcomandparameter
snormal 'SECTION'   snormal tcomandparameter
snormal 'virtual'   snormal tcomandparameter
snormal 'From'   snormal tcomandparameter
snormal 'DIR_Code'   snormal tcomandparameter
snormal 'PSym_code'   snormal tcomandparameter
snormal 'NSym_code'   snormal tcomandparameter
snormal 'NO_points'   snormal tcomandparameter
snormal 'Bias'   snormal tcomandparameter
snormal 'Negative'   snormal tcomandparameter
snormal 'Center'   snormal tcomandparameter
snormal 'Radius'   snormal tcomandparameter
snormal 'Angles'   snormal tcomandparameter
snormal 'SUBDOM'   snormal tcomandparameter
snormal 'MeshMethod'   snormal tcomandparameter
snormal 'RedoAll'   snormal tcomandparameter
snormal 'NoPause'   snormal tcomandparameter
snormal 'MaxFactor'   snormal tcomandparameter
snormal 'MaxLen'   snormal tcomandparameter
snormal 'MaxNoOfIterations'   snormal tcomandparameter
snormal 'SaveToFile'   snormal tcomandparameter
snormal 'IgnoreBIASLine'   snormal tcomandparameter
snormal 'IgnoreBIASArc'   snormal tcomandparameter
snormal 'IgnoreNoPointsLine'   snormal tcomandparameter
snormal 'IgnoreNoPointsArc'   snormal tcomandparameter
snormal 'DefaultFactors'   snormal tcomandparameter
snormal 'MaxAngle'   snormal tcomandparameter
snormal 'MaxPoints'   snormal tcomandparameter
snormal 'SurfacesFactor'   snormal tcomandparameter
snormal 'DivMaxFactor'   snormal tcomandparameter
snormal 'DelMinFactor'   snormal tcomandparameter
snormal 'NewBndPoints'   snormal tcomandparameter
snormal 'DivMax'   snormal tcomandparameter
snormal 'DelMin'   snormal tcomandparameter
snormal 'Full_optim'   snormal tcomandparameter
snormal 'Window'   snormal tcomandparameter
snormal 'solution'   snormal tcomandparameter
snormal 'SolName'   snormal tcomandparameter
snormal 'SolTime'   snormal tcomandparameter
snormal 'EMF'   snormal tcomandparameter
snormal 'Thermal'   snormal tcomandparameter
snormal 'Static'   snormal tcomandparameter
snormal 'Harmonic'   snormal tcomandparameter
snormal 'Transient'   snormal tcomandparameter
snormal 'linear'   snormal tcomandparameter
snormal 'non_linear'   snormal tcomandparameter
snormal 'cont_non_lin'   snormal tcomandparameter
snormal 'cont_lin'   snormal tcomandparameter
snormal 'xy_plane'   snormal tcomandparameter
snormal 'RZ_SP'   snormal tcomandparameter
snormal 'y_sym'   snormal tbackcompatible
snormal 'ZR_SP'   snormal tcomandparameter
snormal 'x_sym'   snormal tbackcompatible
snormal 'RZ_VP'   snormal tcomandparameter
snormal 'ZR_VP'   snormal tcomandparameter
snormal 'GaussOrder'   snormal tcomandparameter
snormal 'BH_CODE'   snormal tcomandparameter
snormal 'B_ini'   snormal tcomandparameter
snormal 'Bini'   snormal tbackcompatible
snormal 'NUR'   snormal tcomandparameter
snormal 'NIUR'   snormal tbackcompatible
snormal 'NU'   snormal tcomandparameter
snormal 'NIU'   snormal tbackcompatible
snormal 'EPS'   snormal tcomandparameter
snormal 'MUR'   snormal tcomandparameter
snormal 'MIUR'   snormal tbackcompatible
snormal 'MU'   snormal tcomandparameter
snormal 'MIU'   snormal tbackcompatible
snormal 'J_val'   snormal tcomandparameter
snormal 'Jval'   snormal tbackcompatible
snormal 'J_exp'   snormal tcomandparameter
snormal 'Jexp'   snormal tbackcompatible
snormal 'Density'   snormal tcomandparameter
snormal 'Dens'   snormal tbackcompatible
snormal 'Sigma'   snormal tcomandparameter
snormal 'CLV'   snormal tcomandparameter
snormal 'Color'   snormal tcomandparameter
snormal 'ColorRgb'   snormal tcomandparameter
snormal 'PM_val'   snormal tcomandparameter
snormal 'BremXY_val'   snormal tcomandparameter
snormal 'BremRT_val'   snormal tcomandparameter
snormal 'PM_pos'   snormal tcomandparameter
snormal 'RefSys'   snormal tbackcompatible
snormal 'RegSys'   snormal tbackcompatible
snormal 'BremXv'   snormal tcomandparameter
snormal 'BremYv'   snormal tcomandparameter
snormal 'BremRv'   snormal tcomandparameter
snormal 'BremTv'   snormal tcomandparameter
snormal 'Spline'   snormal tcomandparameter
snormal 'Velocity'   snormal tcomandparameter
snormal 'Rext'   snormal tcomandparameter
snormal 'Lext'   snormal tcomandparameter
snormal 'Vs'   snormal tcomandparameter
snormal 'C1Val'   snormal tcomandparameter
snormal 'C2Val'   snormal tcomandparameter
snormal 'C3Val'   snormal tcomandparameter
snormal 'AIR_gap'   snormal tcomandparameter
snormal 'Position'   snormal tcomandparameter
snormal 'IntRadius'   snormal tcomandparameter
snormal 'IntCenter'   snormal tcomandparameter
snormal 'ExtRadius'   snormal tcomandparameter
snormal 'ExtCenter'   snormal tcomandparameter
snormal 'NO_Layers'   snormal tcomandparameter
snormal 'Tolerance'   snormal tcomandparameter
snormal 'Tx'   snormal tcomandparameter
snormal 'Tro'   snormal tcomandparameter
snormal 'Ty'   snormal tcomandparameter
snormal 'Tz'   snormal tcomandparameter
snormal 'Moved_Reg'   snormal tcomandparameter
snormal 'Moved_subdom'   snormal tcomandparameter
snormal 'Remeshed_reg'   snormal tcomandparameter
snormal 'Remeshed_subdom'   snormal tcomandparameter
snormal 'Interactive'   snormal tcomandparameter
snormal 'Factor'   snormal tcomandparameter
snormal 'Iterations'   snormal tcomandparameter
snormal 'BMinMax'   snormal tcomandparameter
snormal 'Regions_grouping'   snormal tcomandparameter
snormal 'B_Method'   snormal tcomandparameter
snormal 'Method'   snormal tcomandparameter
snormal 'MeshOrder'   snormal tcomandparameter
snormal 'ShapeOrder'   snormal tcomandparameter
snormal 'ANR_NMK'   snormal tcomandparameter
snormal 'SolFilter'   snormal tcomandparameter
snormal 'NoDraw'   snormal tcomandparameter
snormal 'Step'   snormal tcomandparameter
snormal 'ForWard'   snormal tcomandparameter
snormal 'BackWard'   snormal tcomandparameter
snormal 'Functions'   snormal tcomandparameter
snormal 'AMinMax'   snormal tcomandparameter
snormal 'B_Center'   snormal tcomandparameter
snormal 'FillRegions'   snormal tcomandparameter
snormal 'RegionsFormula'   snormal tcomandparameter
snormal 'Expression'   snormal tcomandparameter
snormal 'AxialLength'   snormal tcomandparameter
snormal 'SiMethod'   snormal tcomandparameter
snormal 'dXdL'   snormal tcomandparameter
snormal 'dYdL'   snormal tcomandparameter
snormal 'PERIOD'   snormal tcomandparameter
snormal 'BAND_OPT'   snormal tcomandparameter
snormal 'iter_max'   snormal tcomandparameter
snormal 'Translation'   snormal tcomandparameter
snormal 'Rotation'   snormal tcomandparameter
snormal 'Point_sym'   snormal tcomandparameter
snormal 'SymCenter'   snormal tcomandparameter
snormal 'Line_sym'   snormal tcomandparameter
snormal 'StartPoint'   snormal tcomandparameter
snormal 'EndPoint'   snormal tcomandparameter
snormal 'LineAngle'   snormal tcomandparameter
snormal 'Replace'   snormal tcomandparameter
snormal 'With'   snormal tcomandparameter
snormal 'DirCodes'   snormal tcomandparameter
snormal 'DIRReplace'   snormal tcomandparameter
snormal 'DIRWith'   snormal tcomandparameter
snormal 'DIRStep'   snormal tcomandparameter
snormal 'Left'   snormal tcomandparameter
snormal 'TOP'   snormal tcomandparameter
snormal 'Scale'   snormal tcomandparameter
snormal 'Additive'   snormal tcomandparameter
snormal 'ChartTitle'   snormal tcomandparameter
snormal 'FromCurves'   snormal tcomandparameter
snormal 'FromMemory'   snormal tcomandparameter
snormal 'FromFile'   snormal tcomandparameter
snormal 'XValues'   snormal tcomandparameter
snormal 'YValues'   snormal tcomandparameter
snormal 'Xlabel'   snormal tcomandparameter
snormal 'YLabels'   snormal tcomandparameter
snormal 'XMinMax'   snormal tcomandparameter
snormal 'YminMax'   snormal tcomandparameter
snormal 'f'   snormal tcomandparameter
snormal 'IntegralMode'   snormal tcomandparameter
snormal 'LossMethod'   snormal tcomandparameter
snormal 'Kc'   snormal tcomandparameter
snormal 'Kh'   snormal tcomandparameter
snormal 'Alfa'   snormal tcomandparameter
snormal 'Beta'   snormal tcomandparameter
snormal 'Kexc'   snormal tcomandparameter
snormal 'Keddy'   snormal tcomandparameter
snormal 'd'   snormal tcomandparameter
snormal 'ro'   snormal tcomandparameter
snormal 'Yes'   snormal tkeyword
snormal 'No'   snormal tkeyword
snormal 'All'   snormal tkeyword
snormal 'Others'   snormal tkeyword
snormal 'ON'   snormal tkeyword
snormal 'OFF'   snormal tkeyword
snormal 'Auto'   snormal tkeyword
snormal 'PositiveTG'   snormal tkeyword
snormal 'FPspreadOut'   snormal tkeyword
snormal 'CCspreadOut'   snormal tkeyword
snormal 'NegativeTG'   snormal tkeyword
snormal 'NotMeshed'   snormal tkeyword
snormal 'New'   snormal tkeyword
snormal 'last'   snormal tkeyword
snormal 'Gp1'   snormal tkeyword
snormal 'Gp3'   snormal tkeyword
snormal 'Gp4'   snormal tkeyword
snormal 'Gp7'   snormal tkeyword
snormal 'Exterior'   snormal tkeyword
snormal 'Interior'   snormal tkeyword
snormal 'SPA'   snormal tkeyword
snormal 'ISPA'   snormal tkeyword
snormal 'DPA'   snormal tkeyword
snormal 'IDPA'   snormal tkeyword
snormal 'O2'   snormal tkeyword
snormal 'Optimal'   snormal tkeyword
snormal 'SelectInteractive'   snormal tkeyword
snormal 'LastSelections'   snormal tkeyword
snormal 'MSI'   snormal tkeyword
snormal 'VW'   snormal tkeyword
snormal 'CVW'   snormal tkeyword
snormal 'Scalar'   snormal tkeyword
snormal 'Vector'   snormal tkeyword
snormal 'Bertotti'   snormal tkeyword
snormal 'Steinmetz'   snormal tkeyword
snormal 'A'   snormal tkeyword
snormal 'T'   snormal tkeyword
snormal 'B'   snormal tkeyword
snormal 'Bx'   snormal tkeyword
snormal 'By'   snormal tkeyword
snormal 'Br'   snormal tkeyword
snormal 'Bt'   snormal tkeyword
snormal 'Bro'   snormal tkeyword
snormal 'Bz'   snormal tkeyword
snormal 'q'   snormal tkeyword
snormal 'qx'   snormal tkeyword
snormal 'qy'   snormal tkeyword
snormal 'qr'   snormal tkeyword
snormal 'qt'   snormal tkeyword
snormal 'qro'   snormal tkeyword
snormal 'qz'   snormal tkeyword
snormal 'G'   snormal tkeyword
snormal 'Gx'   snormal tkeyword
snormal 'Gy'   snormal tkeyword
snormal 'Gr'   snormal tkeyword
snormal 'Gt'   snormal tkeyword
snormal 'Gro'   snormal tkeyword
snormal 'Gz'   snormal tkeyword
snormal 'FDt'   snormal tkeyword
snormal 'FDr'   snormal tkeyword
snormal 'FDx'   snormal tkeyword
snormal 'FDy'   snormal tkeyword
snormal 'FDz'   snormal tkeyword
snormal 'FDro'   snormal tkeyword
snormal 'Pt'   snormal tkeyword
snormal 'Phys'   snormal tkeyword
snormal 'Peddy'   snormal tkeyword
snormal 'Pexc'   snormal tkeyword
snormal 'Pj'   snormal tkeyword
snormal 'Ee'   snormal tkeyword
snormal 'Je'   snormal tkeyword
snormal 'Bn'   snormal tkeyword
snormal 'Btan'   snormal tkeyword
snormal 'BnBtan'   snormal tkeyword
snormal 'X'   snormal tkeyword
snormal 'Y'   snormal tkeyword
snormal 'Z'   snormal tkeyword
snormal 'R'   snormal tkeyword
snormal 'Theta'   snormal tkeyword
snormal 'Area'   snormal tkeyword
snormal 'Triangle'   snormal tkeyword
snormal 'Tri'   snormal tbackcompatible
snormal 'Sub'   snormal tkeyword
snormal 'RegName'   snormal tkeyword
snormal 'Reg'   snormal tbackcompatible
snormal 'RegCode'   snormal tkeyword
snormal 'H'   snormal tkeyword
snormal 'Nr'   snormal tkeyword
snormal 'Tcc'   snormal tkeyword
snormal 'TempRef'   snormal tkeyword
snormal 'LossDensity'   snormal tkeyword
snormal 'MMF'   snormal tkeyword
snormal 'Torque'   snormal tkeyword
snormal 'Force'   snormal tkeyword
snormal 'TForce'   snormal tkeyword
snormal 'NForce'   snormal tkeyword
snormal 'BndTest'   snormal tkeyword
snormal 'J'   snormal tkeyword
snormal 'BremX'   snormal tkeyword
snormal 'BremY'   snormal tkeyword
snormal 'BremR'   snormal tkeyword
snormal 'BremT'   snormal tkeyword
snormal 'PG'   snormal tkeyword
snormal 'Vbr'   snormal tkeyword
snormal 'Vcpc'   snormal tkeyword
snormal 'Vspc'   snormal tkeyword
snormal 'Icsc'   snormal tkeyword
snormal 'Icpc'   snormal tkeyword
snormal 'FluxR'   snormal tkeyword
snormal 'AreaR'   snormal tkeyword
snormal 'IntegralAR'   snormal tkeyword
snormal 'IntegralJR'   snormal tkeyword
snormal 'IntegralJeR'   snormal tkeyword
snormal 'FluxS'   snormal tkeyword
snormal 'AreaS'   snormal tkeyword
snormal 'IntegralAS'   snormal tkeyword
snormal 'IntegralJS'   snormal tkeyword
snormal 'ILoss'   snormal tkeyword
snormal 'Wt'   snormal tkeyword
snormal 'Whys'   snormal tkeyword
snormal 'Weddy'   snormal tkeyword
snormal 'Wexc'   snormal tkeyword
snormal 'Wj'   snormal tkeyword
snormal 'FluxLinkage'   snormal tkeyword
snormal 'VWTorque'   snormal tkeyword
snormal 'VWTForce'   snormal tkeyword
snormal 'VWNForce'   snormal tkeyword
snormal 'MSITorque'   snormal tkeyword
snormal 'MSITForce'   snormal tkeyword
snormal 'MSINForce'   snormal tkeyword
snormal 'EV'   snormal tkeyword
snormal 'GaussQ'   snormal tkeyword
snormal 'Exact'   snormal tkeyword
snormal 'VarIndexList'   snormal tfunction
snormal 'SQRT'   snormal tfunction
snormal 'ROUND'   snormal tfunction
snormal 'ArcSIN'   snormal tfunction
snormal 'ArcCOS'   snormal tfunction
snormal 'ArcTAN'   snormal tfunction
snormal 'PI'   snormal tfunction
snormal 'ABS'   snormal tfunction
snormal 'Truncate'   snormal tfunction
snormal 'SIN'   snormal tfunction
snormal 'COS'   snormal tfunction
snormal 'TAN'   snormal tfunction
snormal 'CTAN'   snormal tfunction
snormal 'LOG'   snormal tfunction
snormal 'EXP'   snormal tfunction
snormal 'SIGN'   snormal tfunction
snormal 'MOD'   snormal tfunction
snormal 'Radians'   snormal tfunction
snormal 'Degrees'   snormal tfunction
snormal 'SortAsc'   snormal tfunction
snormal 'SortDes'   snormal tfunction
snormal 'SUM'   snormal tfunction
snormal 'Prod'   snormal tfunction
snormal 'AVE'   snormal tfunction
snormal 'STD'   snormal tfunction
snormal 'AVESTD'   snormal tfunction
snormal 'XMIN'   snormal tfunction
snormal 'XMax'   snormal tfunction
snormal 'YMIN'   snormal tfunction
snormal 'YMax'   snormal tfunction
snormal 'VarIndexCOUNT'   snormal tfunction
snormal 'UpperCase'   snormal tfunction
snormal 'LowerCase'   snormal tfunction
snormal 'Int'   snormal tfunction
snormal 'Bool'   snormal tfunction
snormal 'Float'   snormal tfunction
snormal 'File'   snormal tfunction
snormal 'CloseOle'   snormal tfunction
snormal 'OpenOle'   snormal tfunction
snormal 'Ole'   snormal tfunction
snormal 'Array'   snormal tfunction
snormal 'Matrix'   snormal tfunction
snormal 'Invert'   snormal tfunction
snormal 'Transpose'   snormal tfunction
snormal 'SolveLSys'   snormal tfunction
snormal 'Delta'   snormal tfunction
snormal 'Show'   snormal tfunction
snormal 'SubMatrix'   snormal tfunction
snormal 'FillData'   snormal tfunction
snormal 'CopyOf'   snormal tfunction
snormal 'Lower'   snormal tfunction
snormal 'Upper'   snormal tfunction
snormal 'LowerDiag'   snormal tfunction
snormal 'UpperDiag'   snormal tfunction
snormal 'Diag'   snormal tfunction
snormal 'MaxVal'   snormal tfunction
snormal 'MinVal'   snormal tfunction
snormal 'MinDim'   snormal tfunction
snormal 'MaxDim'   snormal tfunction
snormal 'XX'   snormal tfunction
snormal 'YY'   snormal tfunction
snormal 'RR'   snormal tfunction
snormal 'TT'   snormal tfunction
snormal 'DOP'   snormal tfunction
snormal 'DOV'   snormal tfunction
snormal 'rep'   snormal tfunction
snormal 'repp'   snormal tfunction
snormal 'repv'   snormal tfunction
snormal 'CrtRep'   snormal tfunction
snormal 'FileExists'   snormal tfunction
snormal 'FindFlag'   snormal tfunction
snormal 'FileOpened'   snormal tfunction
snormal 'EOLN'   snormal tfunction
snormal 'EOF'   snormal tfunction
snormal 'Select'   snormal tfunction
snormal 'XTri'   snormal tfunction
snormal 'YTri'   snormal tfunction
snormal 'RoTri'   snormal tfunction
snormal 'ZTri'   snormal tfunction
snormal 'RadiusTri'   snormal tfunction
snormal 'ThetaTRi'   snormal tfunction
snormal 'ATri'   snormal tfunction
snormal 'TTri'   snormal tfunction
snormal 'BTri'   snormal tfunction
snormal 'BxTri'   snormal tfunction
snormal 'ByTri'   snormal tfunction
snormal 'BroTri'   snormal tfunction
snormal 'BzTri'   snormal tfunction
snormal 'BrTri'   snormal tfunction
snormal 'BtTri'   snormal tfunction
snormal 'HTri'   snormal tfunction
snormal 'MurTri'   snormal tfunction
snormal 'TriCount'   snormal tfunction
snormal 'GetNextTri'   snormal tfunction
snormal 'Links'   snormal tfunction
snormal 'SolCount'   snormal tfunction
snormal 'SolutionsCount'   snormal tfunction
snormal 'SolutionName'   snormal tfunction
snormal 'NotEOS'   snormal tfunction
snormal 'EeTri'   snormal tfunction
snormal 'JeTri'   snormal tfunction
snormal 'Node'   snormal tfunction
snormal 'XNode'   snormal tfunction
snormal 'YNode'   snormal tfunction
snormal 'XYnode'   snormal tfunction
snormal 'RTtoXY'   snormal tfunction
snormal 'Anode'   snormal tfunction
snormal 'tc'   snormal tfunction
snormal 'dt'   snormal tfunction
snormal 'Tnode'   snormal tfunction
snormal 'EIU'   snormal tfunction
snormal 'ERU'   snormal tfunction
snormal 'UF'   snormal tfunction
snormal 'EiF'   snormal tfunction
snormal 'ErF'   snormal tfunction
snormal 'Fourier'   snormal tfunction
snormal 'JERMS'   snormal tfunction
snormal 'ERR'   snormal tfunction
snormal 'StackIndex'   snormal tfunction
snormal 'StackValue'   snormal tfunction
snormal 'StackString'   snormal tfunction
// numbers
snormal [0-9][0-9]*                            snormal  tinteger
snormal \#[0-9A-F]+                            snormal  tinteger
snormal \#\$[0-9A-F]+                            snormal  tinteger
snormal \$[0-9A-F]+                            snormal  tinteger
snormal [1-9][0-9]*\.[0-9]*                    snormal  tfloat
snormal [1-9][0-9]*{\.[0-9]+}|e{[\+\-]}|[0-9]+ snormal  tfloat

//idents
snormal   [a-z_A-Z][a-z_A-Z0-9]*  snormal   tident
//white space
//snormal #32*                      snormal   twhitespace

//comments
snormal   /\*                     scomment1 tcomment
snormal   //                      scomment1 tcomment
scomment1 [#1-#255]*              snormal   tcomment
scomment1 $                       snormal   tcomment
snormal   \{                      scomment2 tcomment
scomment2 [^\}]*                  scomment2 tcomment
scomment2 \}                      snormal   tcomment

snormal   (\*                     scomment3 tcomment
scomment3 [^\*]*                  scomment3 tcomment
scomment3 \*[^)]                  scomment3 tcomment
scomment3 [\*]*)                  snormal   tcomment
scomment3 \*)                     snormal   tcomment

//strings
snormal   \'                      sstring   tstring
sstring   [^\']*                  sstring   tstring
sstring   \'                      snormal   tstring
sstring   \'\'                    sstring   tstring
sstring   $                       snormal   tstring
snormal   "                       sstring2  tstring
sstring2 [^\"]*                   sstring2  tstring
sstring2  "                       snormal   tstring

